spring:
  datasource:
    authentication-manager:
      url: jdbc:postgresql://localhost:5432/authentication-manager
      username: admin
      password: asd123
      driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop