spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication-server
    username: admin
    password: asd123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog.yaml
    liquibase-schema: classpath:db/schema/auth-server-context-schema.sql

app:
  security:
    jwt:
      private-key: prod-key