spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication-server
    username: admin
    password: asd123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

app:
  security:
    jwt:
      private-key: prod-key