spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  liquibase:
    change-log:classpath: classpath:db/changelog/db.changelog.yaml
    liquibase-schema: classpath:db/schema/auth-server-context-schema.sql

app:
  security:
    jwt:
      private-key: dev-key